grpc-host: ":50051"
log-file: auth.log
symmetric-key: "12345123451234512345123451234512"
postgres:
  host: "localhost:5432"
  user: amin
  pass: code
  db-name: rom-db
  ssl: disable
  time-zone: Asia/Tehran

